package:
  version: 0.4.0
  name: chemfiles

about:
  home: https://github.com/chemfiles/chemfiles
  license: MPL-v2.0
  summary: Efficient library for chemistry files IO

requirements:
  run:
    - chemfiles-lib ==0.4.0
    - chemfiles-python ==0.4.0
