package:
  name: chemfiles-python
  version: 0.4.0.dev.764095

build:
  script:  # [not win]
      - export MACOSX_DEPLOYMENT_TARGET=""  # [osx]
      - python setup.py install  # [not win]
  script:  # [win]
      - "%PYTHON%" setup.py install  # [win]
      - if errorlevel 1 exit 1  # [win]
source:
  git_url: https://github.com/chemfiles/chemfiles.py
  git_rev: 76409581a0fb43da06b68b2d2a05ee010387fab4

requirements:
  build:
    - python
    - enum34  # [py < 34]
    - numpy
    - chemfiles-lib
  run:
    - python
    - enum34  # [py < 34]
    - numpy
    - chemfiles-lib

about:
  home: https://github.com/chemfiles/chemfiles.py
  license: MPL-v2.0
  summary: Python binding to chemfiles
