package:
  name: chemfiles-python
  version: 0.4.0

build:
  script:  # [not win]
      - export MACOSX_DEPLOYMENT_TARGET=""  # [osx]
      - python setup.py install  # [not win]
  script:  # [win]
      - "%PYTHON%" setup.py install  # [win]
      - if errorlevel 1 exit 1  # [win]
source:
  git_url: https://github.com/chemfiles/chemfiles.py
  git_rev: 0.4.0

requirements:
  build:
    - python
    - enum34  # [py < 34]
    - numpy
    - chemfiles-lib ==0.4.0
  run:
    - python
    - enum34  # [py < 34]
    - numpy
    - chemfiles-lib ==0.4.0

about:
  home: https://github.com/chemfiles/chemfiles.py
  license: MPL-v2.0
  summary: Python binding to chemfiles
